### PR TITLE
UI Changes

### PR DESCRIPTION
**Pull request by Parsifal-M**
## What type of PR is this?

Please check the category that applies:

- [x] Feature
- [ ] Bug Fix
- [x] Refactor
- [ ] Documentation Update

## Description

In the Open Feedback page, will now display the app.title (or Backstage) instead of always backstage, addresses #26, also created a util to "clean" the URL, removing the noise, so a component location would be for example:

`/catalog/default/component/example-website` a plugin would be `/tech-radar` making it look a little neater.

This also removes the Form component, as I am not sure it would be used... and you'd use the modal over the form...

## Related Issues

#26 

## Testing

- [x] I have included or updated unit tests for my changes.
- [ ] I would like some help writing tests.
- [ ] These changes do not require tests.

### CODE REVIEW

**Comment by Parsifal-M** [comment]
Hey @Baicheng-MiQ!

As a user on this, could I get your opinion here? What do you think?

Thanks!

**Review by Baicheng-MiQ — COMMENTED** [review]
Also noticed you removed `OpenFeedbackForm.tsx`. So it might be worthwhile to update `/backstage-open-feedback/README.md` and `/backstage-open-feedback/plugins/open-feedback/README.md`

**Comment by Parsifal-M** [comment]
> Hey! @Parsifal-M I just reviewed the, and it looks fantastic! I really like the UI changes you’ve made, especially the `cleanUrl` utility and the dynamic app title in the `OpenFeedbackPage`. Just wanted to mention that there might be a potential conflict with the PR #49 I just made on title in the `OpenFeedbackPage`. I'm not quite sure which one looks better.

Yes! also noticed this looking at your PR 😅 

How would you feel about applying some of these changes in your PR and I will close this one? I like your approach more to be able to customise the Title and Subtitle anyway.

If you could implement the cleanUrl in your PR I think we might be good-to-go!

WDYT? 👏

**Comment by Baicheng-MiQ** [comment]
> > Hey! @Parsifal-M I just reviewed the, and it looks fantastic! I really like the UI changes you’ve made, especially the `cleanUrl` utility and the dynamic app title in the `OpenFeedbackPage`. Just wanted to mention that there might be a potential conflict with the PR #49 I just made on title in the `OpenFeedbackPage`. I'm not quite sure which one looks better.
> 
> Yes! also noticed this looking at your PR 😅
> 
> How would you feel about applying some of these changes in your PR and I will close this one? I like your approach more to be able to customise the Title and Subtitle anyway.
> 
> (I will handle removing the FORM in another PR so don't worry about that)
> 
> If you could implement the cleanUrl in your PR I think we might be good-to-go!
> 
> WDYT? 👏

Sounds good! Doing it now.

**Comment by Parsifal-M** [comment]
Closing for now, will come back to this when I have some more time on my plate!

**Pull request closed without merging**
