### PR TITLE
Adding URL Capture Feature

### PR DESCRIPTION
**Pull request by Baicheng-MiQ**
## What type of PR is this?

Please check the category that applies:

- [x] Feature
- [ ] Bug Fix
- [ ] Refactor
- [ ] Documentation Update

## Description

image

This pull request introduces the addition of URL capture functionality to the Open Feedback plugin. It includes modifications across multiple files to ensure that the URL from which feedback is submitted is captured and stored along with other feedback details. This enhancement aims to provide more context to the feedback by associating it with the specific URL where it was submitted.

## Testing

- [x] I have included or updated unit tests for my changes.
- [ ] I would like some help writing tests.
- [ ] These changes do not require tests.

### CODE REVIEW

**Comment by Parsifal-M** [comment]
Hey @Baicheng-MiQ! 👋 

Thanks so much for the contribution! Just wanted to let you know I'm a bit swamped at the moment with other bits, but I have reserved some time this week to look into this!

I will get back to you!

Thanks again 🚀

**Comment by Parsifal-M** [comment]
Hey @Baicheng-MiQ,

Could you run `yarn prettier:write` locally and push again? that should make the CI pass 😄 

Thank you!

**Comment by Baicheng-MiQ** [comment]
> Hey @Baicheng-MiQ,
> 
> Could you run `yarn prettier:write` locally and push again? that should make the CI pass 😄
> 
> Thank you!

Thank you so much @Parsifal-M !
Just done that!

**Comment by Parsifal-M** [comment]
Hello @Baicheng-MiQ!

Thanks again for your patience and help on this, I've had a quick look today and I think it's a really cool idea, and I just have a couple of questions/suggestions 🙏

Can we make the URL optional? I think it's a good idea to have it in the form, this way you could point to an entity or plugin via the URL for more "targeted" feedback, but I think it's best to keep it optional just in case it's more general/generic feedback which maybe doesn't directly link to a single location (URL) we could use a placeholder text or something like "optional location URL" maybe you can think of some better wording 😅

Secondly, I'm quite curious what inspired you to contribute this feature? 😄

Thanks again for taking the time to contribute! 🚀

**Comment by Baicheng-MiQ** [comment]
> Hello @Baicheng-MiQ!
> 
> Thanks again for your patience and help on this, I've had a quick look today and I think it's a really cool idea, and I just have a couple of questions/suggestions 🙏
> 
> Can we make the URL optional? I think it's a good idea to have it in the form, this way you could point to an entity or plugin via the URL for more "targeted" feedback, but I think it's best to keep it optional just in case it's more general/generic feedback which maybe doesn't directly link to a single location (URL) we could use a placeholder text or something like "optional location URL" maybe you can think of some better wording 😅
> 
> Secondly, I'm quite curious what inspired you to contribute this feature? 😄
> 
> Thanks again for taking the time to contribute! 🚀

Hi @Parsifal-M 

Sorry for the delay. I was so busy for the past week.

But I've made the URL optional in the new commit. Instead of always showing the URL field, I added a checkbox that allows users to hide or show the URL field. This should make it flexible for both targeted and general feedback.

As for the inspiration behind this feature, our company needs more insights into feedback, particularly where it happens, so I forked your repo and added this new feature.

Thanks again for the feedback and support! 🚀

**Comment by Parsifal-M** [comment]
> > Hello @Baicheng-MiQ!
> > Thanks again for your patience and help on this, I've had a quick look today and I think it's a really cool idea, and I just have a couple of questions/suggestions 🙏
> > Can we make the URL optional? I think it's a good idea to have it in the form, this way you could point to an entity or plugin via the URL for more "targeted" feedback, but I think it's best to keep it optional just in case it's more general/generic feedback which maybe doesn't directly link to a single location (URL) we could use a placeholder text or something like "optional location URL" maybe you can think of some better wording 😅
> > Secondly, I'm quite curious what inspired you to contribute this feature? 😄
> > Thanks again for taking the time to contribute! 🚀
> 
> Hi @Parsifal-M
> 
> Sorry for the delay. I was so busy for the past week.
> 
> But I've made the URL optional in the new commit. Instead of always showing the URL field, I added a checkbox that allows users to hide or show the URL field. This should make it flexible for both targeted and general feedback.
> 
> As for the inspiration behind this feature, our company needs more insights into feedback, particularly where it happens, so I forked your repo and added this new feature.
> 
> Thanks again for the feedback and support! 🚀

Hey! 👋 

No problem!

Awesome! Thats great to hear.

I will put together a release this weekend 🤞 so should be good to use next week!

Thanks so much for your help!

**Comment by Parsifal-M** [comment]
Hey @Baicheng-MiQ 👋 

Made some slight adjustments, what do you think?

LMK! 🥳

**Comment by Baicheng-MiQ** [comment]
> Hey @Baicheng-MiQ 👋
> 
> Made some slight adjustments, what do you think?
> 
> LMK! 🥳

That look great to me!!! 🤞

Happy weekend!!!

**Pull request merged**
